name: zadanko
description: Zadanie rekrutacyjne

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  logger: ^1.1.0
  intl: ^0.17.0
  dartz: ^0.10.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  retrofit_generator: ^4.2.0
  pretty_dio_logger: ^1.1.1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_flavor: ^3.1.1
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  gap: ^2.0.1
  flutter_inappwebview: ^5.7.2+3
  linkify: ^4.1.0


dev_dependencies:
  build_runner: ^2.3.0
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.2
  intl_utils: ^2.7.0


  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Translation
  arb_dir: lib/app/utils/translations/l10n
  output_dir: lib/app/utils/translations/generated